### ISSUE TITLE
Datepickers are not generated (javascript calendar and clock)

### ISSUE THREAD

**Issue by laraaj** [django-admin-bootstrapped/django-admin-bootstrapped#168]
Hello,

It's really an amazing work how you transformed the admin area with bootstrap, thank you so much for 
sharing your great work.
But the javascript calendar and clock icons are not inject when using bootstrap with my admin area.
but when i disable bootstrap they appear here is the code:

<span class="datetimeshortcuts">&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(0, 0);">Today</a>&nbsp;|&nbsp;<a id="calendarlink0" href="javascript:DateTimeShortcuts.openCalendar(0);"><img alt="Calendar" src="/static/admin/img/icon_calendar.gif"></a></span>

I'm using Python 2.7.3 and Django 1.7.1 in a python virtual environment, i already run the command
"python manage.py collectstatic" inside the virtual environment shell. it moved all static files to the 
static directory of my site, and no files are missing according to the browser debugging logs.

so is the problem because of an incompatibility with the version of Django or python I'm using 
or is it a missing feature in your integration. 

Thank yous o much for your support and your very good work.

**Comment by pulsarav** [comment]
Hello, i have the same problem here if i add this line under settings.py 
DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer', the date picker is gone im using django 1.7 and python 2.7.3 thru and nginex server.

thanks

**Comment by LRPalacios** [comment]
I can confirm the same issue when adding the line :DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

**Comment by xrmx** [comment]
Guys if any of you can point a meaningful error that would be easier to track down and eventually fix.

**Comment by LRPalacios** [comment]
I hope this helps, 

Simple installing and adding to the installed apps this package,  produce for a DateTimeField an output like this in the admin:

![screenshot_1](https://cloud.githubusercontent.com/assets/4844997/7539577/2ec81be8-f565-11e4-8698-4c68f83c374d.png)

and it works just fine, but if as you suggest in the documentation for a better boostrap experience:

"For a full bootstrap3 experience you may want to use a custom renderer for the fields. There's one available in tree that requires the django-bootstrap3 application installed. You have to add to your project settings file:  
DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'"

once i install the django-bootstrap3 add the above constant in settings the output in the admin is like this:

![screenshot_2](https://cloud.githubusercontent.com/assets/4844997/7539745/3f7c4f12-f566-11e4-8312-79a8ac4bbda2.png)

as the original author of the issue suggested the problem is there is no clock icon nor calendar icon,


i am using python 3.4.2, django 1.7.7, django-admin-bootstrapped==2.4.0, django-bootstrap3==5.4.0, there is no console error, no not founds not anything

**Comment by xrmx** [comment]
@LRPalacios thanks! now it's clear to me that the issue in django-bootstrap3 trying to render a SplitDateTimeWidget. Will try to fix.

**Comment by xrmx** [comment]
Opened a pull request for django-bootstrap3 here:
https://github.com/dyve/django-bootstrap3/pull/253
Some changes are required on our side too

**Comment by xrmx** [comment]
Hi there, could you please double check latest git works for you? thanks!

**Comment by iliashko** [comment]
Hello xrmx, 
Could you tell me which version that obtains the fix I should download?
In my admin page I see the datetimefield as a single text box and not as a "AdminSplitDateTime".

I'm using django_admin_bootstrapped==2.5.6, bootstrap3_datetime==2.2.3, django_bootstrap3==6.2.2, django 1.8 and python 3.4.

Thanks!

**Comment by xrmx** [comment]
@iliashko 2.5.1 see milestone field in the right column, or just read the CHANGELOG. The bug here was about missing js calendar widget not missing input fields so please check if you can reproduce this with the shipped test project, i'd start with removing bootstrap3_datetime.

**Comment by iliashko** [comment]
@xrmx , thanks for you reply.
I'm new to Django and trying to make my admin page to work properly with django-admin-bootstrapped.
I'm actually having trouble with modifying a DateTimeField to work with the bootstrap3_datetime widget, and i'm not sure regarding to where I should ask about bootstrap3_datetime.

I've posted it in stackoverflow but didn't get any answers. If you could take a look and point me to the right direction, that would help tremendously.
http://stackoverflow.com/questions/33445868/django-bootstrap3-datetime-widget-in-admin-site-doesnt-pass-form-data

Thanks again.

**Comment by xrmx** [comment]
@iliashko you should ask to bootstrap3_datetime developers, asking here to fix your own issues it not how it is supposed to work. Good luck!
