### ISSUE TITLE
How to theme or customize bootstrap CSS?

### ISSUE THREAD

**Issue by bformet** [django-admin-bootstrapped/django-admin-bootstrapped#176]
First thank you for the great project, 

What is the preferred way to use a theme or custom bootstrap css?

Is there some kind of settings or template override possibility?

Thanks again

**Comment by xrmx** [comment]
There's only one way to override templates which is the django one :) So if you need to overwrite the templates just stick your app providing the templates before django-admin-bootstrapped application in the INSTALLED_APPS. If you need improvements that may be useful to others feel free to describe your needs in more details.

**Comment by bformet** [comment]
django-bootstrap3 comes with a handy dict [variable in settings.py](http://django-bootstrap3.readthedocs.org/en/latest/settings.html) allowing to configure various aspects of bootstrap.
I was hoping something similar for django-admin-bootstrapped though I'm just looking for a way to improve the look of the bootstrapped admin. I'll give it a watch to template override.

**Comment by xrmx** [comment]
Well ui improvements are appreciated here :) If you want to customize template for your company, you probably want to change base.html and add a custom bootstrap theme instead of the one shipped by default. Regarding the configurability i'd like to keep things as simple as possible, especially since in django 1.9 it would be easier to extend templates.
